site_name: TEST
site_url: https://azurelearn1.github.io/testdocs/
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.indexes

repo_url: https://github.com/AzureLearn1/testdocs
repo_name: testdocs

plugins:
  - search